  MyEC2Instance: 
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: "ami-074251216af698218"
      KeyName: "udacity"
      BlockDeviceMappings: 
      - DeviceName: "/dev/sdm"
        Ebs: 
          VolumeType: "io1"
          Iops: "200"
          VolumeSize: "20"
      - DeviceName: "/dev/sdk"
        NoDevice: {}